# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Tree Sequence Tutorials
author: Tskit Developers
logo: _static/tskit_logo.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 300

# Information about where the book exists on the web
repository:
  url: https://github.com/tskit-dev/tutorials
  branch: main

launch_buttons:
  binderhub_url: ""

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

only_build_toc_files: true

sphinx:
    extra_extensions:
    - sphinx.ext.todo
    - sphinx.ext.intersphinx
    - IPython.sphinxext.ipython_console_highlighting
    config:
      html_theme: tskit_book_theme
      pygments_style: monokai
      todo_include_todos: true
      intersphinx_mapping:
        py: ["https://docs.python.org/3", null]
        tskit: ["https://tskit.dev/tskit/docs/stable", null]
        msprime: ["https://tskit.dev/msprime/docs/stable", null]
        pyslim: ["https://tskit.dev/pyslim/docs/stable", null]
        numpy: ["https://numpy.org/doc/stable/", null]
      myst_enable_extensions:
      - colon_fence
      - deflist
      - dollarmath
